---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: fluent-logging-global
  layeringDefinition:
    abstract: true
    layer: global
  labels:
    hosttype: fluent-logging-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh_infra.fluent_logging
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh_infra.fluent_logging
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.elasticsearch
      dest:
        path: .values.endpoints.elasticsearch
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.fluentd
      dest:
        path: .values.endpoints.fluentd
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.prometheus_fluentd_exporter
      dest:
        path: .values.endpoints.prometheus_fluentd_exporter
    # Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.elasticsearch.admin
      dest:
        path: .values.endpoints.elasticsearch.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.elasticsearch.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_elasticsearch_admin_password
        path: .

data:
  chart_name: fluent-logging
  release: fluent-logging
  namespace: osh-infra
  wait:
    timeout: 900
    labels:
      release_group: airship-fluent-logging
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-fluent-logging
      create: []
    post:
      create: []
  values:
    labels:
      fluentd:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      fluentbit:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_fluentd_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    dependencies:
      static:
        fluentbit:
          jobs: ""
          services:
            - endpoint: internal
              service: fluentd
        fluentd:
          jobs: ""
          services:
            - endpoint: internal
              service: elasticsearch
    manifests:
      job_elasticsearch_template: false
    conf:
      fluentbit:
        - service:
            header: service
            Flush: 5
            Daemon: Off
            Log_Level: info
            Parsers_File: parsers.conf
        - ceph_cluster_logs:
            header: input
            Name: tail
            Tag: ceph.cluster.*
            Path: /var/log/ceph/ceph.log
            DB: /var/log/ceph.db
            Parsers: syslog
            Mem_Buf_Limit: 5MB
            DB.Sync: Normal
            Buffer_Chunk_Size: 1M
            Buffer_Max_Size: 1M
        - ceph_audit_logs:
            header: input
            Name: tail
            Tag: ceph.audit.*
            Path: /var/log/ceph/ceph.audit.log
            DB: /var/log/ceph.db
            Parsers: syslog
            Mem_Buf_Limit: 5MB
            DB.Sync: Normal
            Buffer_Chunk_Size: 1M
            Buffer_Max_Size: 1M
        - ceph_mon_logs:
            header: input
            Name: tail
            Tag: ceph.mon.*
            Path: /var/log/ceph/ceph-mon**.log
            DB: /var/log/ceph.db
            Parsers: syslog
            Mem_Buf_Limit: 5MB
            DB.Sync: Normal
            Buffer_Chunk_Size: 1M
            Buffer_Max_Size: 1M
        - ceph_osd_logs:
            header: input
            Name: tail
            Tag: ceph.osd.*
            Path: /var/log/ceph/ceph-osd**.log
            DB: /var/log/ceph.db
            Parsers: syslog
            Mem_Buf_Limit: 5MB
            DB.Sync: Normal
            Buffer_Chunk_Size: 1M
            Buffer_Max_Size: 1M
        - containers_tail:
            header: input
            Name: tail
            Tag: kube.*
            Path: /var/log/containers/*.log
            Parser: docker
            DB: /var/log/flb_kube.db
            DB.Sync: Normal
            Buffer_Chunk_Size: 1M
            Buffer_Max_Size: 1M
            Mem_Buf_Limit: 5MB
        - kube_filter:
            header: filter
            Name: kubernetes
            Match: kube.*
            Merge_JSON_Log: On
        - fluentd_output:
            header: output
            Name: forward
            Match: "*"
            Host: ${FLUENTD_HOST}
            Port: ${FLUENTD_PORT}
      td_agent:
        - metrics_agent:
            header: source
            type: monitor_agent
            bind: 0.0.0.0
            port: 24220
        - fluentbit_forward:
            header: source
            type: forward
            port: "#{ENV['FLUENTD_PORT']}"
            bind: 0.0.0.0
        - ceph_elasticsearch:
            header: match
            type: elasticsearch
            user: "#{ENV['ELASTICSEARCH_USERNAME']}"
            password: "#{ENV['ELASTICSEARCH_PASSWORD']}"
            expression: "ceph**"
            include_tag_key: true
            host: "#{ENV['ELASTICSEARCH_HOST']}"
            port: "#{ENV['ELASTICSEARCH_PORT']}"
            logstash_format: true
            logstash_prefix: ceph
            buffer_chunk_limit: 10M
            buffer_queue_limit: 32
            flush_interval: "20"
            max_retry_wait: 300
            disable_retry_limit: ""
            num_threads: 8
            type_name: ceph_logs
        - elasticsearch:
            header: match
            type: elasticsearch
            user: "#{ENV['ELASTICSEARCH_USERNAME']}"
            password: "#{ENV['ELASTICSEARCH_PASSWORD']}"
            expression: "**"
            include_tag_key: true
            host: "#{ENV['ELASTICSEARCH_HOST']}"
            port: "#{ENV['ELASTICSEARCH_PORT']}"
            logstash_format: true
            buffer_chunk_limit: 10M
            buffer_queue_limit: 32
            flush_interval: "20"
            max_retry_wait: 300
            disable_retry_limit: ""
            num_threads: 8
      parsers:
        - syslog:
            header: parser
            Name: syslog
            Format: regex
            Regex: '^(?<time>.*[0-9]{2}:[0-9]{2}:[0-9]{2}) (?<host>[^ ]*) (?<app>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? (?<log>.+)$'
            Time_Key: time
            Time_Format: "%Y-%m-%dT%H:%M:%S.%L"
            Time_Keep: On
            Types: "pid:integer"
  dependencies:
    - osh-infra-helm-toolkit
...
