---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-dns-scaled
  layeringDefinition:
    abstract: false
    layer: type
  storagePolicy: cleartext
data:
  description: Scale out coredns to a daemonset
  chart_group:
    - coredns-scaled
...
