---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova
  replacement: true
  labels:
    component: nova
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: nova-cruiser
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      logging:
        logger_nova:
          level: INFO
...
