---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-rabbitmq
  labels:
    name: openstack-rabbitmq-global
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Deploy RabbitMQ
  chart_group:
    - openstack-rabbitmq
