---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-crt
  schema: metadata/Document/v1
  storagePolicy: cleartext
schema: deckhand/Certificate/v1
data: |
  -----BEGIN CERTIFICATE-----
  MIIKHzCCCQegAwIBAgIQBFXjMtjww8WQVvneL6OYdzANBgkqhkiG9w0BAQsFADBN
  MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5E
  aWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMjAwMzE4MDAwMDAwWhcN
  fhY/b1UwBxgp7b9O8Ul7gifC8x/mzLR0rxy/BDGN8VVQeydhkKIPiUz39p4mJEns
  3Q+6YNx1098ZgsZsI4l0hjYAspMsjxXmOqzBmqK9vaHj/9FAUyQVnx4mWKuBwdl0
  VBSr
  -----END CERTIFICATE-----
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-ca
  schema: metadata/Document/v1
  storagePolicy: cleartext
schema: deckhand/CertificateAuthority/v1
data: |
  -----BEGIN CERTIFICATE-----
  MIIElDCCA3ygAwIBAgIQAf2j627KdciIQ4tyS8+8kTANBgkqhkiG9w0BAQsFADBh
  c+LJMto4JQtV05od8GiG7S5BNO98pVAdvzr508EIDObtHopYJeS4d60tbvVS3bR0
  j6tJLp07kzQoH3jOlOrHvdPJbRzeXDLz
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
  MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
  BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
  TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
  DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
  hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
  06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
  PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
  YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
  CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
  -----END CERTIFICATE-----
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-key
  schema: metadata/Document/v1
  storagePolicy: cleartext
schema: deckhand/CertificateKey/v1
data: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAl8edCT/6suqpokycZecKZyCIi3yubV8Qq140+K65csrmb9Rl
  uir1A0CUjM1BKYtOttXIsXmlx9TZuC1RChY4A5++sXA+/7iJwp+YVbYak7hO7CGH
  oPaX+zNRdTk+/UXq7um2hnjCZfQwYUzy8RqvIrXnS2GzX/x2k141GEYl2FBzwwfd
  6CQrOFSFYBdY4AZcZtgKNmqCUin7vsd8crOAJklQ3LCxSr0gfxUpOloBzpm+wdq6
  EaCXhErz870GBnEvmc+Qyru85SKcrf4LdbXKDLWKW+OkZF5U0MG+cr/ummebaZxR
  TW3B7ok3EAQgsXMJToAmKbN4m6ZZSJxiqcX6HO2ppHa0ELGutvCp
  -----END RSA PRIVATE KEY-----
...
