---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: heat
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: heat-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      logging:
        logger_heat:
          level: INFO
...
