---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: osh-infra-monitoring
  labels:
    name: osh-infra-monitoring-cruiserlite
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: osh-infra-monitoring-chart-group-global
    actions:
      - method: replace
        path: .chart_group
  storagePolicy: cleartext
data:
  chart_group:
    - prometheus
    - prometheus-node-exporter
    - prometheus-kube-state-metrics
    - prometheus-process-exporter
    - nagios
