---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-osd-sde
  labels:
    name: ucp-ceph-osd-sde-nc
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-ceph-osd-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: ucp-ceph-osd-sde
  release: ucp-ceph-osd-sde
  wait:
    labels:
      release_group: clcp-ucp-ceph-osd-sde
  values:
    daemonset:
      prefix_name: "clcp-ucp-ceph-osd-sde"
    conf:
      storage:
        failure_domain_by_hostname: 1-8
        osd:
          - data:
              type: bluestore
              location: /dev/sde
            block_db:
              location: /dev/sdb
              size: "96GB"
            block_wal:
              location: /dev/sdb
              size: "2GB"
...

