---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-prometheus-openstack-exporter
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Prometheus OpenStack Exporter for UCP Namespace
  chart_group:
    - ucp-prometheus-openstack-exporter
