---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-osd-global
  layeringDefinition:
    abstract: true
    layer: global
  storagePolicy: cleartext
  labels:
    name: tenant-ceph-osd-global
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tenant-ceph-osd
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.tenant-ceph-osd
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .values.network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .values.network.cluster
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.tenant_ceph_mon
      dest:
        path: .values.endpoints.ceph_mon
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.tenant_ceph_mgr
      dest:
        path: .values.endpoints.ceph_mgr
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
    - dest:
       path: .values.conf.ceph.global.fsid
      src:
        schema: deckhand/Passphrase/v1
        name: tenant_ceph_fsid
        path: .

data:
  chart_name: tenant-ceph-osd
  release: tenant-ceph-osd
  namespace: tenant-ceph
  protected:
    continue_processing: true
  wait:
    timeout: 900
    labels:
      release_group: airship-tenant-ceph-osd
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      osd:
        node_selector_key: tenant-ceph-osd
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: openstack
      object_store:
        namespace: openstack
      ceph_mon:
        namespace: tenant-ceph
      ceph_mgr:
        namespace: tenant-ceph
      fluentd:
        namespace: osh-infra
    monitoring:
      ceph_mgr:
        port: 9284
    bootstrap:
      enabled: true
    conf:
      storage:
        mon:
          directory: /var/lib/openstack-helm/tenant-ceph/mon
        osd:
          - data:
              type: directory
              location: /var/lib/openstack-helm/tenant-ceph/osd/osd-one
            journal:
              type: directory
              location: /var/lib/openstack-helm/tenant-ceph/osd/journal-one
      osd:
        # NOTE(alanmeadows): This is required ATM for bootstrapping a Ceph
        # cluster with only one OSD.  Depending on OSD targeting & site
        # configuration this can be changed.
        osd_crush_chooseleaf_type: 0
      ceph:
        osd:
          osd_op_num_threads_per_hdd: 2
          osd_op_num_threads_per_ssd: 4
  dependencies:
    - tenant-ceph-htk
...
