---
# OVS-DPDK NOTE:
#   Add ovs-dpdk section to specify images and charts needed
#   to support deployment of ovs-dpdk

schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: software-versions
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: software-versions-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  kernel_drivers:
    ixgbe_driver:
      type: tar
      location: https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.6.3/ixgbe-5.6.3.tar.gz
...
