---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-infra
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Common UCP Components
  chart_group:
    - ucp-ingress
    - ucp-mariadb
    - ucp-postgresql
    - ucp-rabbitmq
    - ucp-keystone-memcached
...
