---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: postgres-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.postgresql-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: postgres-htk
  release: postgres-htk
  namespace: postgres-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
