---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-tiller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tiller
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.tiller
      dest:
        path: .values.images.tags

data:
  chart_name: tiller
  release: ucp-tiller
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 600
    labels:
      release_group: clcp-ucp-tiller
    native:
      # Note(seaneagan): This allows the stnadalone tiller to update the tiller
      # chart's release status to DEPLOYED before the standalone tiller goes
      # away, in case armada is using it (as opposed to the armada sidecar
      # tiller), otherwise the tiller chart can get stuck in PENDING_UPGRADE
      # status.
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-ucp-tiller
  values:
    conf:
      tiller:
        storage: secret

  dependencies:
    - tiller-htk
...
