---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tiller-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tiller-htk
      dest:
        path: .source
data:
  chart_name: tiller-htk
  release: tiller-htk
  namespace: tiller-htk
  values: {}
  dependencies: []
...
