---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: glance
  labels:
    name: glance-global
    component: glance
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.glance
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.glance
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.image
      dest:
        path: .values.endpoints.image
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.image_registry
      dest:
        path: .values.endpoints.image_registry
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_messaging
      dest:
        path: .values.endpoints.oslo_messaging
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.ceph_object_store
      dest:
        path: .values.endpoints.ceph_object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.glance
      dest:
        path: .values.endpoints.identity.auth.glance
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.test
      dest:
        path: .values.endpoints.identity.auth.test
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.oslo_messaging.admin
      dest:
        path: .values.endpoints.oslo_messaging.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.oslo_messaging.glance
      dest:
        path: .values.endpoints.oslo_messaging.auth.glance
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.oslo_db
      dest:
        path: .values.endpoints.oslo_db.auth.glance
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.oslo_db.database
      dest:
        path: .values.endpoints.oslo_db.path
        pattern: DB_NAME
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.glance.ceph_object_store
      dest:
        path: .values.endpoints.ceph_object_store.auth.glance
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.image.name
      dest:
        path: .values.endpoints.oslo_messaging.path
        pattern: VHOST_NAME

    #Glance Image
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.glance.cirros_image
      dest:
        - path: .values.conf.rally_tests.tests
          pattern: CIRROS_IMAGE_LOCATION
          recurse:
            depth: -1

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_glance_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.test.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_glance_test_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_messaging_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_messaging.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_glance_oslo_messaging_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_glance_oslo_db_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_db_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_cache.auth.memcache_secret_key
      src:
        schema: deckhand/Passphrase/v1
        name: osh_oslo_cache_secret_key
        path: .
    - dest:
        path: .values.endpoints.object_store.auth.glance.tmpurlkey
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
    - dest:
        path: .values.endpoints.ceph_object_store.auth.glance.tmpurlkey
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .
    - dest:
        path: .values.endpoints.ceph_object_store.auth.glance.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_glance_password
        path: .
data:
  chart_name: glance
  release: glance
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: clcp-glance
    resources:
      - type: job
      - type: deployment
        min_ready: 100%
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-glance
    post:
      create: []
  test:
    enabled: true
  values:
    dependencies:
      static:
        rabbit_init:
          services:
            - endpoint: internal
              service: oslo_messaging
          jobs:
            - clcp-openstack-rabbitmq-cluster-wait
    pod:
      replicas:
        api: 3
        registry: 3
      affinity:
        anti:
          type:
            api: requiredDuringSchedulingIgnoredDuringExecution
            registry: requiredDuringSchedulingIgnoredDuringExecution
      lifecycle:
        upgrades:
          deployments:
            pod_replacement_strategy: RollingUpdate
            rolling_update:
              max_unavailable: 50%
    labels:
      api:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      registry:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    manifests:
      job_bootstrap: false
      deployment_registry: true
      ingress_registry: true
      pdb_registry: true
      service_ingress_registry: true
      service_registry: true
    ceph_client:
      configmap: tenant-ceph-etc
      user_secret_name: pvc-tceph-client-key
    conf:
      rabbitmq:
        policies:
          - vhost: "glance"
            name: "ha_ttl_glance"
            definition:
              ha-mode: "all"
              ha-sync-mode: "automatic"
              message-ttl: 70000
            priority: 0
            apply-to: all
            pattern: '^(?!(amq\.|reply_)).*'
      rally_tests:
        run_tempest: false
        tests:
          GlanceImages.create_and_delete_image:
            - args:
                container_format: bare
                disk_format: qcow2
                image_location: CIRROS_IMAGE_LOCATION
              runner:
                concurrency: 1
                times: 1
                type: constant
              sla:
                failure_rate:
                  max: 0
          GlanceImages.create_and_list_image:
            - args:
                container_format: bare
                disk_format: qcow2
                image_location: CIRROS_IMAGE_LOCATION
              runner:
                concurrency: 1
                times: 1
                type: constant
              sla:
                failure_rate:
                  max: 0
      glance:
        DEFAULT:
          enable_v1_api: true
          enable_v1_registry: true
          enable_v2_api: true
          enable_v2_registry: true
        oslo_middleware:
          enable_proxy_headers_parsing: true
        audit_middleware_notifications:
          driver: log
      logging:
        loggers:
          keys:
            - root
            - glance
            - oslo.messaging
        handlers:
          keys:
            - stdout
            - stderr
            - "null"
        formatters:
          keys:
            - context
            - default
        logger_root:
          level: WARNING
          handlers: "null"
        logger_glance:
          level: INFO
          handlers:
            - stdout
          qualname: glance
        logger_oslo.messaging:
          level: INFO
          handlers:
            - stdout
          qualname: oslo.messaging
        logger_amqp:
          level: WARNING
          handlers: stderr
          qualname: amqp
        logger_amqplib:
          level: WARNING
          handlers: stderr
          qualname: amqplib
        logger_eventletwsgi:
          level: WARNING
          handlers: stderr
          qualname: eventlet.wsgi.server
        logger_sqlalchemy:
          level: WARNING
          handlers: stderr
          qualname: sqlalchemy
        logger_boto:
          level: WARNING
          handlers: stderr
          qualname: boto
        handler_null:
          class: logging.NullHandler
          formatter: default
          args: ()
        handler_stdout:
          class: StreamHandler
          args: (sys.stdout,)
          formatter: context
        handler_stderr:
          class: StreamHandler
          args: (sys.stderr,)
          formatter: context
        formatter_context:
          class: oslo_log.formatters.ContextFormatter
        formatter_default:
          format: "%(message)s"
      policy:
        context_is_admin: role:admin or role:admin_support or role:admin_viewer
        admin_create: role:admin or role:admin_support
        admin_read: role:admin or role:admin_support or role:admin_viewer
        admin_update: role:admin
        admin_delete: role:admin
        admin_snapshot: role:admin
        tenant_create: role:snapshot_member or role:_member_ or role:sriov_member or role:support_member or rule:admin_create
        tenant_snapshot_create: role:snapshot_member or rule:admin_create
        tenant_snapshot_delete: role:snapshot_member or rule:admin_delete
        tenant_read: role:snapshot_member or role:_member_  or role:sriov_member or role:support_member or role:viewer or rule:admin_read
        tenant_update: role:snapshot_member or role:_member_ or role:sriov_member or rule:admin_update
        tenant_delete: role:snapshot_member or role:_member_ or role:sriov_member or rule:admin_delete
        tenant_modify_action: role:_member_ or role:sriov_member or rule:tenant_snapshot_create
        admin_or_owner: role:admin or project_id:%(project_id)s
        default: role:admin
        add_image: rule:tenant_snapshot_create or role:tenant_glance_create
        delete_image: rule:tenant_snapshot_delete or role:tenant_glance_delete
        get_image: rule:tenant_read or role:tenant_glance_read
        get_images: rule:tenant_read or role:tenant_glance_read
        modify_image: rule:tenant_snapshot_create or role:tenant_glance_create
        publicize_image: rule:admin_create or role:admin_glance_create
        communitize_image: rule:admin_create or role:admin_glance_create
        copy_from: rule:admin_create or role:admin_glance_create
        download_image: rule:tenant_create or role:tenant_glance_create
        upload_image: rule:tenant_snapshot_create or role:tenant_glance_create
        delete_image_location: rule:admin_delete or role:admin_glance_delete
        get_image_location: rule:tenant_create or role:tenant_glance_create
        set_image_location: rule:admin_create or role:admin_glance_create
        add_member: rule:tenant_create or role:tenant_glance_create
        delete_member: rule:tenant_update or role:tenant_glance_update
        get_member: rule:tenant_read or role:tenant_glance_read
        get_members: rule:tenant_read or role:tenant_glance_read
        modify_member: rule:tenant_create or role:tenant_glance_create
        manage_image_cache: rule:admin_update or role:admin_glance_update
        get_task: rule:tenant_read or role:tenant_glance_read
        get_tasks: rule:tenant_read or role:tenant_glance_read
        add_task: rule:admin_create or role:admin_glance_create
        modify_task: rule:admin_create or role:admin_glance_create
        tasks_api_access: role:admin
        deactivate: rule:admin_update or role:admin_glance_update
        reactivate: rule:admin_update or role:admin_glance_update
        get_metadef_namespace: rule:tenant_read or role:tenant_glance_read
        get_metadef_namespaces: rule:tenant_read or role:tenant_glance_read
        modify_metadef_namespace: rule:tenant_modify_action or role:tenant_glance_update
        add_metadef_namespace: rule:tenant_create or role:tenant_glance_create
        delete_metadef_namespace: rule:tenant_delete or role:tenant_glance_delete
        get_metadef_object: rule:tenant_read or role:tenant_glance_read
        get_metadef_objects: rule:tenant_read or role:tenant_glance_read
        modify_metadef_object: rule:tenant_modify_action or role:tenant_glance_update
        add_metadef_object: rule:tenant_create or role:tenant_glance_create
        delete_metadef_object: rule:tenant_delete or role:tenant_glance_delete
        list_metadef_resource_types: rule:tenant_read or role:tenant_glance_read
        get_metadef_resource_type: rule:tenant_read or role:tenant_glance_read
        add_metadef_resource_type_association: rule:tenant_create or role:tenant_glance_create
        delete_metadef_resource_type_association: rule:tenant_delete or role:tenant_glance_delete
        get_metadef_property: rule:tenant_read or role:tenant_glance_read
        get_metadef_properties: rule:tenant_read or role:tenant_glance_read
        modify_metadef_property: rule:tenant_modify_action or role:tenant_glance_update
        add_metadef_property: rule:tenant_create or role:tenant_glance_create
        delete_metadef_property: rule:tenant_delete or role:tenant_glance_delete
        get_metadef_tag: rule:tenant_read or role:tenant_glance_create
        get_metadef_tags: rule:tenant_read or role:tenant_glance_create
        modify_metadef_tag: rule:tenant_modify_action or role:tenant_glance_update
        add_metadef_tag: rule:tenant_create or role:tenant_glance_create
        add_metadef_tags: rule:tenant_create or role:tenant_glance_create
        delete_metadef_tag: rule:tenant_delete or role:tenant_glance_delete
        delete_metadef_tags: rule:tenant_delete or role:tenant_glance_delete
  dependencies:
    - os-glance-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: os-glance-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.glance-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: os-glance-htk
  release: os-glance-htk
  namespace: os-glance-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
