---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: full-site-global
  layeringDefinition:
    abstract: true
    layer: global
  labels:
    name: full-site-global
  storagePolicy: cleartext
data:
  release_prefix: clcp
  chart_groups:
    - podsecuritypolicy
    - kubernetes-proxy
    - kubernetes-container-networking
    - kubernetes-dns
    - kubernetes-etcd
    - kubernetes-haproxy
    - kubernetes-core
    # - kubernetes-falco
    - ingress-kube-system
    - ucp-ceph-update
    - ucp-ceph-config
    # TODO(aw442m): Move mini-mirror after UCP components once mini-mirror MOP
    # has been removed from Divingbell post-1.7. Mini-mirror must be deployed
    # deployed before Divingbell in all 1.7 releases.
#    - mini-mirror
    - ucp-divingbell
    - ucp-infra
    - ucp-keystone
    - ucp-armada
    - ucp-services
#    - ucp-nc-info
    - ucp-prometheus-openstack-exporter
#   - gstools-setup
#   - gstools-login
#   - gstools-services
#    - gstools-capacityplanning
#    - gstools-roles
#    - gstools-cphalo
#    - gstools-bpa
    - osh-infra-ingress-controller
    - osh-infra-ceph-config
    - osh-infra-radosgw
    - osh-infra-logging
    - osh-infra-monitoring
    - osh-infra-mariadb
    - osh-infra-dashboards
    - openstack-ingress-controller
    - openstack-ceph-config
    - openstack-tenant-ceph
    - openstack-mariadb
    - openstack-rabbitmq
    - openstack-memcached
    - openstack-compute-services
    - openstack-keystone
    - openstack-radosgw
    - openstack-glance
    - openstack-cinder
    - openstack-compute-kit
    - openstack-heat
    - osh-infra-prometheus-openstack-exporter
    - openstack-horizon
    - openstack-barbican
    - utilities
    - sonobuoy
...
