---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: glance
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: glance-global
    actions:
    - method: merge
      path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      logging:
        logger_glance:
          level: INFO
...
