---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  labels:
    name: chartgroup-ucp-keystone-global
data:
  description: UCP Keystone
  chart_group:
    - ucp-keystone
...
