---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: full-site
  labels:
    name: full-site
    layer: type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: full-site-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  release_prefix: clcp
  chart_groups:
    - podsecuritypolicy
    - kubernetes-proxy
    - kubernetes-container-networking
    - kubernetes-dns-scaled
    - kubernetes-etcd
    - kubernetes-haproxy
    - kubernetes-core
    - ingress-kube-system
    - ucp-ceph-update
    - ucp-ceph-config
    - ucp-divingbell
    - ucp-infra
    - ucp-keystone
    - ucp-armada
    - ucp-services-scaled
    - osh-infra-ingress-controller
    - osh-infra-ceph-config
    - osh-infra-radosgw
    - osh-infra-logging
    - osh-infra-monitoring
    - osh-infra-mariadb
    - osh-infra-dashboards
    - openstack-ingress-controller
    - openstack-ceph-config
    - openstack-tenant-ceph
    - openstack-mariadb
    - openstack-rabbitmq
    - openstack-memcached
    - openstack-keystone
    - openstack-radosgw
    - openstack-glance
    - openstack-cinder
    - openstack-compute-kit
    - openstack-heat
    - openstack-horizon
#depends on all pods being deployed, up and running and thus needs to run last
...
