---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-deckhand-scaled
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-deckhand-global
    actions:
      - method: merge
        path: .
  labels:
    name: ucp-deckhand-scaled-type
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        deckhand: 2
...
