---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-shipyard-scaled
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-shipyard-global
    actions:
      - method: merge
        path: .
  labels:
    name: ucp-shipyard-scaled-type
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        shipyard:
          api: 2
        airflow:
          worker: 2
          # Set replicas to 0 to disable the standalone scheduler
          scheduler: 0
...
