apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../airship-core/shared/catalogues

# NOTE(drewwalters96): Uncomment to patch common-networking catalogue.
# patchesStrategicMerge:
#   - common-networking.yaml
# Uncomment to patch versions catalogue once needed
# patchesStrategicMerge:
#   - versions.yaml

