---
schema: deckhand/PublicKey/v1
metadata:
  schema: metadata/Document/v1
  name: dell_repo_key
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
#
# pub   rsa4096 2012-03-02 [SC]
#       42550ABD1E80D7C1BC0BAD851285491434D8786F
# uid                      Dell Inc., PGRE 2012 (PG Release Engineering Build Group 2012) <PG_Release_Engineering@Dell.com>
# sub   rsa4096 2012-03-02 [E]
#
data: |-
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  Comment: GPGTools - https://gpgtools.org

  mQINBE9RLYYBEADEAmJvn2y182B6ZUr+u9I29f2ue87p6HQreVvPbTjiXG4z2/k0
  l/Ov0DLImXFckaeVSSrqjFnEGUd3DiRr9pPb1FqxOseHRZv5IgjCTKZyj9Jvu6bx
  U9WL8u4+GIsFzrgS5G44g1g5eD4Li4sV46pNBTp8d7QEF4e2zg9xk2mcZKaT+STl
  O0Q2WKI7qN8PAoGd1SfyW4XDsyfaMrJKmIJTgUxe9sHGj+UmTf86ZIKYh4pRzUQC
  WBOxMd4sPgqVfwwykg/y2CQjrorZcnUNdWucZkeXR0+UCR6WbDtmGfvN5H3htTfm
  Nl84Rwzvk4NT/By4bHy0nnX+WojeKuygCZrxfpSqJWOKhQeH+YHKm1oVqg95jvCl
  vBYTtDNkpJDbt4eBAaVhuEPwjCBsfff/bxGCrzocoKlh0+hgWDrr2S9ePdrwv+rv
  2cgYfUcXEHltD5Ryz3u5LpiC5zDzNYGFfV092xbpG/B9YJz5GGj8VKMslRhYpUjA
  IpBDlYhOJ+0uVAAKPeeZGBuFx0A1y/9iutERinPx8B9jYjO9iETzhKSHCWEov/yp
  X6k17T8IHfVj4TSwL6xTIYFGtYXIzhInBXa/aUPIpMjwt5OpMVaJpcgHxLam6xPN
  FYulIjKAD07FJ3U83G2fn9W0lmr11hVsFIMvo9JpQq9aryr9CRoAvRv7OwARAQAB
  tGBEZWxsIEluYy4sIFBHUkUgMjAxMiAoUEcgUmVsZWFzZSBFbmdpbmVlcmluZyBC
  dWlsZCBHcm91cCAyMDEyKSA8UEdfUmVsZWFzZV9FbmdpbmVlcmluZ0BEZWxsLmNv
  bT6IRgQQEQoABgUCT1E0sQAKCRDKd5UdI7ZqnSh9AJ9jXsuabnqEfz5DQwWbmMDg
  aLGXiwCfXA9nDiBc1oyCXVabfbcMs8J0ktqIRgQTEQIABgUCT1FCzwAKCRAhq+73
  kvD8CSnUAJ4j3Q6r+DESBbvISTD4cX3WcpMepwCfX8oc1nHL4bFbVBS6BP9aHFcB
  qJ6IXgQQEQoABgUCT1E0yQAKCRB1a6cLEBnO1iQAAP98ZGIFya5HOUt6RAxL3TpM
  RSP4ihFVg8EUwZi9m9IVnwD/SXskcNW1PsZJO/bRaNVUZIUniDIxbYuj5++8KwBk
  sZiJATMEEAEIAB0WIQRxCo8h7EfAD++yLEknxOa1pRUD0AUCW96h9AAKCRAnxOa1
  pRUD0AK2B/46mCjWgyEHDylacNbnxHjpsFQICF/v9YJb7rXhDDSebYUT6rL1Rb7Y
  LG9y7ojKb+EuabALtFMPnjJ8exjSTc/jCFn6WXWzE0CWYnMIazO2ChQXdIudajVT
  roQW3eHeU7OI2RWnBQq+A42T7tUI1KNXQ+jPfib/nrMBWZFyq3A69A8fyXlzDBsv
  XsCCFF/8Wup4BEyMDI+NTW/yr7qgBagi//wtYsERBVwp/GjwkhYF1nUHR1gCueZ1
  YduSU7LcR41wM7GYFhz75x5jDiw4W50TxenCtLlhmo8QHeaC5NdS3SC5W90Di4kf
  aNktmHRZe88siXiZE9Ui9f9TUigB4uBziQIcBBABCAAGBQJPUThwAAoJENl7K6iG
  oQzApQkQAIWOfWvARCEFEfaFXkBvFzWY2iAJ8m6u/yMXhTJGCq9GbKMRcvgQx15d
  m2o6pSC53fSGGsbCw4fvJcDkwYh4VnzYOG/eoAz4OYeF2h4Gfsz5izLhC/4UKCnW
  CmQ5jNW9GIp6FeSorKL6QuSGYtQLQBbORC/vjcrBnmN0X3yKcpxUbFKJmZgcdhs/
  fcZIlF4G0/WlwCUyn7EKxSwEjOi1Ym/6AN0sdTEFxhVNyAOucnv1FwOAOd3UmxN5
  tdEWAWaHkugVEPchbZkcm2bYm1uUTThmQg+v0Nz8uubclnlFHkYispLACpdSBqW9
  msAN6wG6zXf8Xt6gH0fjTJZ4nbVOJyTtxhugex0z0HxqfHOvfmFWjDC9yXMrwAgi
  X1QtGi4Pq7ulJAg0n1qbqoHTCa4ZtdhTNeq9V92hcAwNasJwkHLFiVjGp6g/JYx5
  d0tlXdJ8j3C2bBhrmX0wrCvab4XdxQDQucp3MHuaItbnolNyqyFn7yNPDcwrI/B9
  mQgDyqc+dc2Xw4G5TBVx05gzWVo+EKxxtNSzg3vpmZ7AhawVm4j9dxMLCfVgDGei
  /v4sCY46IvXuCA5kzgSXRlKFihC2DH4JaReRDxlHLGGgPRX3EgoJvUEd9SMcvhfe
  W4Qk1U9uscE7TTGBXWdqzEYwP03kzX5eShy4umLwILTGgU/J2CsHiQI3BBMBCgAh
  BQJPUS2GAhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEBKFSRQ02HhvXgcP
  /2rGzOCkcQXxYvUZs0TYrTohRDdRak2xObo4zfvZvThG/rQd2Rcb9GxD29pFHaRM
  LTKugoAuZ/FHC23uUxfNh6PK9plWDUYeUZbXbwLQytqUMQjofotm/YpuhqCGWtR1
  jZCryoltHZomGAb1pbu/IkPCaSIsUSB18BHXdZ0CIFsY1YsddVQ6/oRFz0RUTCMk
  czLXoqtsP1zU1GQIdu+QWmU5i3TC6GD4RzvfQJGILHGvQyvX9M+0mAZsYKygLPbq
  DZ66KOFMaHYwhWRw7vlBtnnz+0ryZ6vb+l2gu2cagRvADmxLMKhmi7/QDd7eKC41
  oawCKDVsCDNS1qWC5ioxWJSx2n99DGISfCexh84MQDZ5Dj+INEYl3mDS3Db7GRl2
  etfys7rxOmHLBl0jFSkVWsS1pIEuefTkoxHEFdUw+uW/m7bSHhBGJnEvIyyi/qtk
  9akyp5g+lbjQrWcJbMY0ecB58TkY7prQuZG5LdZcY29JdoDb093HAOhRFikv7r7Z
  XkA3hhRAOpqyhBqA+Ka0MJYz1dDGcMs1qnJTpTO4NtYv/klI/DQ9iMNHQrOC7x5H
  +BdZTXVd0AeNWUBq20KnAnCRZt6kbGIYuHYPPtuI92za0h48aLBrXJji79eY1wNW
  8clx5J9Bzxuj2du3aILCZwA9RlxB9kvMoSXJWLi9CRNAuQINBE9RL+EBEADZXBfH
  W1zGur10ps55xEhKLSdjkZr6+UdcxIKkCTmfQ8jC/UQHNHZreyMIMFDV/hH2PC4V
  yyrx1q49pgV5tutQPUlPIo0DjxxQIP0mMj9eian0sdo7L1hgSIxFxeGd0lvyQ9Mg
  TQF5Vi1kRp93ceHB8sZnhowgHP+rd9tk8ouVy7cChsQP7xB3rhpk7iszSBJ1mW3Z
  6gC3K0/8Sujxow6OOVSsfJsy2pf5p3F5r2jVRMpXfDDMEH5GCR72V8KVmF2lk4AI
  jDJvshHdIGgWSUTwUghE2M/WxDXj1hDJ63fSOuaUZeF9u7LQ0PdcjtnSHX2plarY
  uN+mby3NC+BGex1rYzed74F6G8TM8+P+nh+9QUSboxtcmBJNidQ1CSldVlH1fDsN
  E7CVTUETPy/b/IpkjHYkddgY8x4rJkXjL2ngFn1C+0NbYML5GRBbbd7JfKNHqAd/
  UfMT+KdWQKSRUY+jd68gk1UMOd+kBRhG/gudTHSW1xUg00RxZQRVbK0hOj8QduEW
  kPt+8N5UGaf8gqBqgOe0uVVSAIwJZeGJd+O1pjV/Ux6II4Yc7i5F1vsDRiD1/Up2
  aKVQH7nOIY9E5Y1Wuq22LYsOh2TZr769f70kDLgMpfh5BJqmgIQ4FZJ29zEKlEJs
  3jv1rYEqmEi2+6T8AymMuyNQaIzYjrfqjI+j+QARAQABiQIeBBgBCgAJBQJPUS/h
  AhsMAAoJEBKFSRQ02Hhv+pgP+Kug00i8ICg4lWCEaamnFMEC8krnzqAMRkhHXvLx
  kaXBhAvpFrdWqiIhOI3ZcRR+wquUp8KIyqXASyALyGJOsfcKH8+XMddLOVx6tSWt
  oyiVdiD0+WXSalgXPjPCuSyXpXpmEWaHudGk9I2zeWBUVJLlNHGWcqr/fLWc02Dv
  YXRuLB+IEmYODjplLZz9ccEqi1nQ39EaZ4w7sTMCTOJuht1G2kOMNSvIb1LWaPbg
  vfpSx6uHj/YHMZ74u14OpiN1FwF4i2F11jWNPZGF0P4466S8b1iD8JOs29No7Lg9
  PI+Ex6eZFOJ37o4/xpJXqxiSadcqSDhMFePsXJAHihlASBzqckKtX5+W8/CIrbkh
  d8UsXU9qnzBrKF5r36NpfE/UHZj8nW+GRmIb9uBhUGaMjAAEy23z5ir1yQKqJkm6
  dEVI3kQqJu3Ww9RXy0W7aUQ+98x2qwYWGGTSwzJbNyCEExbkbzXie13xsIZEhOK7
  WPdSfd3jO+8Ta+LF3mBvkUMeMuR8/fUP4C2rNnHpT+mafGODhAnb3l9wQNMrSPC9
  NsJKCfIsWZ6RrJDJeANFGCOMOI2f83anaXPcD4ZD4/Y/nhdlCJ81jmr7glzZkM9V
  pCz/6pUfA3ISbVCpYGavU4bISuIExEjZ5sc3aUeqWCRmxA3RcmRXucR0Vkpawt1k
  284=
  =ZcSP
  -----END PGP PUBLIC KEY BLOCK-----
...
