---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-scheduler
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.scheduler
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.scheduler
      dest:
        path: .values.images.tags

    # Kube-scheduler Log Level
    - src:
        schema: nc/CorridorConfig/v1
        name: corridor-config
        path: .kubernetes_components.scheduler_log_level
      dest:
        path: .values.scheduler.logging.log_level

    # CA
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: kubernetes
        path: .
      dest:
        path: .values.secrets.tls.ca

    # Certificates
    - src:
        schema: deckhand/Certificate/v1
        name: scheduler
        path: .
      dest:
        path: .values.secrets.tls.cert
    - src:
        schema: deckhand/CertificateKey/v1
        name: scheduler
        path: .
      dest:
        path: .values.secrets.tls.key

data:
  chart_name: scheduler
  release: kubernetes-scheduler
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 900
    labels:
      release_group: clcp-kubernetes-scheduler
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-kubernetes-scheduler
  values:
    network:
      kubernetes_netloc: 127.0.0.1:6553
    pod:
      lifecycle:
        upgrades:
          daemonsets:
            pod_replacement_strategy: RollingUpdate
            scheduler:
              enabled: true
              min_ready_seconds: 0
              max_unavailable: 50%
  dependencies:
    - scheduler-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: scheduler-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.scheduler-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: scheduler-htk
  release: scheduler-htk
  namespace: scheduler-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
