---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  labels:
    ingress: kube-system
    name: cluster-ingress-global
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.ingress
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.ingress
      dest:
        path: .values.images.tags
data:
  chart_name: ingress-kube-system
  release: ingress-kube-system
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 600
    labels:
      release_group: clcp-ingress-kube-system
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-ingress-kube-system
  values:
    labels:
      server:
        node_selector_key: kube-ingress
        node_selector_value: enabled
      error_server:
        node_selector_key: kube-ingress
        node_selector_value: enabled
    deployment:
      mode: cluster
      type: DaemonSet
    network:
      host_namespace: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "603"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Content-Type-Options: 'nosniff'";
            more_set_headers "X-Frame-Options: 'deny'";
            more_set_headers "Content-Security-Policy: script-src 'self'";
            more_set_headers "X-Permitted-Cross-Domain-Policies: none";
            more_clear_headers "Server";
    pod:
      replicas:
        error_page: 2
  dependencies:
    - ingress-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.ingress-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: ingress-htk
  release: ingress-htk
  namespace: ingress-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
