---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone-scaled
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-keystone-global
    actions:
      - method: merge
        path: .
  labels:
    name: ucp-keystone-scaled-type
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        api: 2
    endpoints:
      oslo_messaging:
        statefulset:
          replicas: 2
...
