---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: calicoctl-utility
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.utility.calicoctl-utility
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.utility.calicoctl-utility
      dest:
        path: .values.images.tags
    # Certificates
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.ca
    - src:
        schema: deckhand/Certificate/v1
        name: calico-node
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.crt
    - src:
        schema: deckhand/CertificateKey/v1
        name: calico-node
        path: .
      dest:
        path: .values.endpoints.etcd.auth.client.tls.key
    # Location corridor
    - src:
        schema: pegleg/CommonSoftwareConfig/v1
        name: common-software-config
        path: .location.location_corridor
      dest:
        path: .values.conf.utility.location_corridor
    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.endpoints.etcd.host_fqdn_override.default
data:
  chart_name: calicoctl-utility
  release: calicoctl-utility
  namespace: utility
  protected:
    continue_processing: true
  wait:
    timeout: 600
    labels:
      release_group: clcp-calicoctl-utility
  install:
   no_hooks: false
  upgrade:
   no_hooks: false
  values:
    labels:
      utility:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    endpoints:
      etcd:
        hosts:
          default: calico-etcd
        scheme:
          default: https
    manifests:
      configmap_bin: true
      configmap_etc_client: true
      deployment_calicoctl_utility: true
      job_image_repo_sync: false
      secret_certificates: true
  dependencies:
    - calicoctl-utility-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: calicoctl-utility-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.utility.calicoctl-utility-htk
      dest:
        path: .source
data:
  chart_name: calicoctl-utility-htk
  release: calicoctl-utility-htk
  namespace: calicoctl-utility-htk
  values: {}
  dependencies: []
...
