---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ncct-utility
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: ncct-utility-global
    component: utility
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.utility.ncct-utility
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.utility.ncct-utility
      dest:
        path: .values.images.tags
    # Location corridor
    - src:
        schema: nc/CorridorConfig/v1
        name: corridor-config
        path: .utility.always_log_user
      dest:
        path: .values.conf.utility.always_log_user
data:
  chart_name: ncct-utility
  release: ncct-utility
  namespace: utility
  protected:
    continue_processing: false
  wait:
    timeout: 600
    labels:
      release_group: clcp-ncct-utility
  install:
   no_hooks: false
  upgrade:
   no_hooks: false
  values:
    labels:
      utility:
        node_selector_key: utility
        node_selector_value: enabled
    manifests:
      configmap_bin: true
      configmap_ncct_etc: true
      deployment_ncct_utility: true
      job_image_repo_sync: false
...
