---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-utility
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: openstack-utility-global
    component: utility
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.utility.openstack-utility
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.utility.openstack-utility
      dest:
        path: .values.images.tags

    # Log User Openstack Utility Container
    - src:
        schema: nc/CorridorConfig/v1
        name: corridor-config
        path: .utility.always_log_user
      dest:
        path: .values.conf.utility.always_log_user

data:
  chart_name: openstack-utility
  release: openstack-utility
  test:
    enabled: false
  namespace: utility
  protected:
    continue_processing: false
  wait:
    timeout: 600
    labels:
      release_group: clcp-openstack-utility
  install:
   no_hooks: false
  upgrade:
   no_hooks: false
   pre:
      delete:
        - type: job
          labels:
            release_group: clcp-openstack-utility
  values:
    labels:
      utility:
        node_selector_key: utility
        node_selector_value: enabled
  dependencies:
    - openstack-utility-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-utility-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.utility.openstack-utility-htk
      dest:
        path: .source
data:
  chart_name: openstack-utility-htk
  release: openstack-utility-htk
  namespace: openstack-utility-htk
  values: {}
  dependencies: []
...
