- op: replace
  path: /providers/0/versions/v0.3.2
  value:  ../airshipctl/manifests/function/capm3/v0.3.2
- op: replace
  path: /providers/1/versions/v0.3.7
  value:  ../airshipctl/manifests/function/cabpk/v0.3.7
- op: replace
  path: /providers/2/versions/v0.3.7
  value:  ../airshipctl/manifests/function/capi/v0.3.7
- op: replace
  path: /providers/3/versions/v0.3.7
  value:  ../airshipctl/manifests/function/cacpk/v0.3.7

