---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-falco
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Kubernetes falco
  sequenced: true
  chart_group:
    - kubernetes-falco
