---
# This file is the source information for the service accounts used by
# components of Network Cloud.
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: ucp_service_accounts
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  ucp:
    postgres:
      admin:
        username: postgres
      replica:
        username: standby
      audit:
        username: audit
    prometheus_postgresql_exporter:
      user:
        username: postgresql_exporter
    oslo_db:
      admin:
        username: root
      sst:
        username: sst
      audit:
        username: audit
    prometheus_mysql_exporter:
      user:
        username: ucp-oslodb-exporter
    oslo_messaging:
      admin:
        username: rabbitmq
    keystone:
      admin:
        region_name: RegionOne
        username: admin
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      test:
        region_name: RegionOne
        role: admin
        username: keystone-test
        project_name: test
        user_domain_name: default
        project_domain_name: default
      oslo_messaging:
        admin:
          username: rabbitmq
        keystone:
          username: keystone
      oslo_db:
        username: keystone
        database: keystone
    promenade:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: promenade
    drydock:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: drydock
      postgres:
        username: drydock
        database: drydock
    webhook:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: webhook
    shipyard:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: shipyard
      postgres:
        username: shipyard
        database: shipyard
    airflow:
      postgres:
        username: airflow
        database: airflow
      oslo_messaging:
        admin:
          username: rabbitmq
        user:
          username: airflow
    maas:
      admin:
        username: admin
        email: none@none
      postgres:
        username: maas
        database: maasdb
    barbican:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: barbican
      oslo_db:
        username: barbican
        database: barbican
      oslo_messaging:
        admin:
          username: rabbitmq
        keystone:
          username: keystone
    armada:
      keystone:
        project_domain_name: default
        user_domain_name: default
        project_name: service
        region_name: RegionOne
        role: admin
        username: armada
    deckhand:
      keystone:
        region_name: RegionOne
        role: admin
        project_name: service
        project_domain_name: default
        user_domain_name: default
        username: deckhand
      postgres:
        username: deckhand
        database: deckhand
    prometheus_openstack_exporter:
      user:
        role: admin
        username: prometheus-openstack-exporter
        project_name: service
        user_domain_name: default
        project_domain_name: default
  ceph:
    swift:
      keystone:
        role: admin
        region_name: RegionOne
        username: swift
        project_name: service
        user_domain_name: default
        project_domain_name: default
...
---
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: aqua_service_accounts
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  aqua:
    orchestrator:
      role: admin
      username: geppetto
      project_name: aqua-admin
      user_domain_name: qa
      project_domain_name: qa
    executor:
      username: pinocchio
...
