---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-infra-mariadb
  labels:
    name: openstack-infra-mariadb-global
    component: mariadb
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.mariadb
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.mariadb
      dest:
        path: .values.images.tags

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.oslo_db
      dest:
        path: .values.endpoints.oslo_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_infra_endpoints
        path: .osh_infra.prometheus_mysql_exporter
      dest:
        path: .values.endpoints.prometheus_mysql_exporter
    # Accounts
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.oslo_db.admin
      dest:
        path: .values.endpoints.oslo_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.oslo_db.sst
      dest:
        path: .values.endpoints.oslo_db.auth.sst
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.oslo_db.audit
      dest:
        path: .values.endpoints.oslo_db.auth.audit
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.prometheus_mysql_exporter.user
      dest:
        path: .values.endpoints.oslo_db.auth.exporter
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_infra_service_accounts
        path: .osh_infra.prometheus_mysql_exporter.user
      dest:
        path: .values.endpoints.prometheus_mysql_exporter.auth.user

    # Secrets
    - dest:
        path: .values.endpoints.oslo_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_oslo_db_admin_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.sst.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_oslo_db_sst_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.audit.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_oslo_db_audit_password
        path: .
    - dest:
        path: .values.endpoints.oslo_db.auth.exporter.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_oslo_db_exporter_password
        path: .
    - dest:
        path: .values.endpoints.prometheus_mysql_exporter.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_infra_oslo_db_exporter_password
        path: .

data:
  chart_name: osh-infra-mariadb
  release: osh-infra-mariadb
  namespace: osh-infra
  wait:
    timeout: 1800
    labels:
      release_group: clcp-osh-infra-mariadb
    resources:
      - type: job
      - type: statefulset
        min_ready: 66%
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    options:
      force: true
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-osh-infra-mariadb
  values:
    volume:
      size: 30Gi
      backup:
        size: 50Gi
    monitoring:
      prometheus:
        enabled: true
    pod:
      replicas:
        error_page: 2
      affinity:
        anti:
          type:
            server: requiredDuringSchedulingIgnoredDuringExecution
            ingress: requiredDuringSchedulingIgnoredDuringExecution
            ingress-error-pages: requiredDuringSchedulingIgnoredDuringExecution
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      prometheus_mysql_exporter:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      lifecycle:
        upgrades:
          deployments:
            pod_replacement_strategy: RollingUpdate
            rolling_update:
              max_unavailable: 50%
    manifests:
      cron_job_mariadb_backup: true
      pvc_backup: true
  dependencies:
    - osh-infra-mariadb-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: osh-infra-mariadb-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.mariadb-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: osh-infra-mariadb-htk
  release: osh-infra-mariadb-htk
  namespace: osh-infra-mariadb-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
